baseURL = "https://bougiefever.azurewebsites.net/"
languageCode = "en-us"
title = "Bougiefever"
theme = "bootstrap4"
enableRobotsTXT = true

copyright = "Copyright &copy; 2018 - Annie Bougie"
canonifyurls = true

paginate = 3

summaryLength = 30
enableEmoji = true
enableGitInfo = true
pygmentsCodeFences = true

[permalinks]
  posts = "/:year/:month/:slug/"
  page = "/:slug/"

[author]
    # Site Author
    name = "Annie Bougie"
    github = "https://github.com/Bougiefever/bougiefeverblog"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = ""
    instagram = ""

[params]
    tagline = "All things Azure"
    background_color_class = "bg-black"
    featured_image = "/images/computer-data-analytics-blue-background-website-header.jpg"
    recent_posts_number = 5
    author = "Annie Bougie" 
    description = "Sharing my learnings."
    date_format = "Mon Jan 02, 2006"

[frontmatter]
    date = ["date", "publishDate", "lastmod"]
    lastmod = [":git", "lastmod", "date", "publishDate"]
    publishDate = ["publishDate", "date"]
    expiryDate = ["expiryDate"]